# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Boise Dance
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  All things Dance in Boise. Find places to dance in Boise, take dance lessons in Boise, locate Boise Dance Studios, find dance instructors in Boise, attend Boise dance events. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# permalink: /:slug.html

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: no-style-please
# See config details here https://github.com/riggraz/no-style-please/blob/master/_config.yml
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "Boise.Dance" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
breadcrumb_separator: "&gt;"
plugins:
  - jekyll-feed

collections:
  groups:
    output: true
    permalink: /:collection/:name
  studios:
    output: true
    permalink: /:collection/:name
  venues:
    output: true
    permalink: /:collection/:name
  lessons:
    output: true
    permalink: /:collection/:name
    sort_by: order
  events:
    output: true
    permalink: /:collection/:name
defaults:
  - 
    scope:
      type: groups
    values:
      layout: entity
      breadcrumb: groups
  -
    scope:
      type: studios
    values:
      layout: entity
      breadcrumb: studios
  - scope:
      type: venues
    values:
      layout: entity
      breadcrumb: venues
  - scope:
      type: lessons
    values:
      layout: entity
      breadcrumb: lessons
  - 
    scope:
      type: events
    values:
      layout: entity
      breadcrumb: events

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
